export const usersList = [
  {
    id: 1,
    name: "Chiquita F. Jacobs",
    username: "chiquitajacobs@gmail.com",
    password: "chiquitaf",
    isLogged: false,
    lastLogged: "",
    role: "ADMIN",
  },
  {
    id: 2,
    name: "Breanna Y. Wilkerson",
    username: "breannawilkerson@gmail.com",
    password: "breannay",
    isLogged: false,
    lastLogged: "",
    role: "USER",
  },
  {
    id: 3,
    name: "Brielle F. Oneill",
    username: "brielleoneill@gmail.com",
    password: "briellef",
    isLogged: false,
    lastLogged: "",
    role: "USER",
  },
  {
    id: 4,
    name: "Bernard B. Guthrie",
    username: "bernardguthrie@gmail.com",
    password: "bernardb",
    isLogged: false,
    lastLogged: "",
    role: "USER",
  },
  {
    id: 5,
    name: "Steven S. Wilcox",
    username: "stevenwilcox@gmail.com",
    password: "stevensw",
    isLogged: false,
    lastLogged: "",
    role: "USER",
  },
];

export const leavesList = [
  {
    username: "breannawilkerson@gmail.com",
    leaveType: "Earned Leave",
    startDate: "2021-01-09",
    endDate: "2021-01-13",
    leaveCount: 4,
    createdBy: "Breanna Y. Wilkerson",
    status: "Approved",
    createdAt: 1613332310473,
  },
  {
    username: "bernardguthrie@gmail.com",
    leaveType: "Sick Leave",
    startDate: "2021-02-04",
    endDate: "2021-02-05",
    leaveCount: 2,
    createdBy: "Bernard B. Guthrie",
    status: "Pending",
    createdAt: 1613332420653,
  },
  {
    username: "stevenwilcox@gmail.com",
    leaveType: "Sick Leave",
    startDate: "2021-02-10",
    endDate: "2021-02-11",
    leaveCount: 2,
    createdBy: "Steven S. Wilcox",
    status: "Pending",
    createdAt: 1613323220567,
  },
  {
    username: "stevenwilcox@gmail.com",
    leaveType: "Earned Leave",
    startDate: "2021-01-16",
    endDate: "2021-01-17",
    leaveCount: 2,
    createdBy: "Steven S. Wilcox",
    status: "Pending",
    createdAt: 1613332345623,
  },
  {
    username: "brielleoneill@gmail.com",
    leaveType: "Earned Leave",
    startDate: "2021-01-15",
    endDate: "2021-01-20",
    leaveCount: 6,
    createdBy: "Brielle F. Oneill",
    status: "Approved",
    createdAt: 1613332337845,
  },
  {
    username: "breannawilkerson@gmail.com",
    leaveType: "Sick Leave",
    startDate: "2021-02-09",
    endDate: "2021-02-10",
    leaveCount: 2,
    createdBy: "Breanna Y. Wilkerson",
    status: "Pending",
    createdAt: 1613332378326,
  },
];
